version: '3.1'

services:

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  # server:
  #   image: paperclip_server
  #   ports:
  #     - 5000:5000
  #     - "5001-5100:5001-5100/udp"
  #     - "2020-2050:2020-2050/udp"
  #   links:
  #     - db
  #   depends_on:
  #     - db